### list all
GET https://YOUR-APP-NAME.onrender.com/api/persons

### info
GET https://YOUR-APP-NAME.onrender.com/info

### single
GET https://YOUR-APP-NAME.onrender.com/api/persons/1

### create
POST https://YOUR-APP-NAME.onrender.com/api/persons
Content-Type: application/json

{
  "name": "Render Tester",
  "number": "555-0000"
}

### delete
DELETE https://YOUR-APP-NAME.onrender.com/api/persons/1
